version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    networks:
      - app-net
    restart: always
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads

networks:
  app-net:
    driver: bridge
