version: '3'
services:
  app:
    container_name: vitalityshare-app
    build:
      context: .
    ports:
      - "3000:3000" 
    networks:
      - vitalityshare-net
    restart: always
    env_file:
      - .env

networks:
  vitalityshare-net:
    driver: bridge
